import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Search from '../components/search'
import { getSortedPostsData } from '../lib/posts'

export default function Home({ allPostsData }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Post Searcher App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to the <a href="#">Post Searcher</a>
                </h1>

                <p className={styles.description}>
                  Through this tool you can easily search for posts!
                </p>

                <Search documents={allPostsData}/>

                <ul>
                    {allPostsData.map(({ id, date, title, text }) => (
                        <li key={id} className={styles.grid}>
                            <Link href={`/posts/${id}`}>
                                <div className={styles.card}>
                                    <h2>{title}</h2>
                                    <p>{text}</p>
                                    Posted on: {date}
                                </div>
                            </Link>
                        </li>
                    ))}
                </ul>
            </main>
            <footer className={styles.footer}>
                <a href="https://www.classyllama.com/" target="_blank">
                    Made with passion
                    <span className={styles.logo}>
                        <Image src="/llama.svg" alt="Llama Logo" width={108} height={24} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export async function getServerSideProps() {
    const allPostsData = getSortedPostsData()
    return {
        props: {
            allPostsData
        }
    }
}
